# Generated by Django 5.1.1 on 2024-11-02 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAndDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian'), ('PESCATARIAN', 'Pescatarian'), ('OMNIVORE', 'Omnivore'), ('MEAT_HEAVY', 'Meat-Heavy')], max_length=25)),
                ('dairy_meat_meal_frequency', models.PositiveIntegerField(default=0)),
                ('food_source', models.CharField(choices=[('ALWAYS', 'Always'), ('OFTEN', 'Often'), ('SOMETIMES', 'Sometimes'), ('RARELY', 'Rarely'), ('NEVER', 'Never')], max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_and_diet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeEnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_situation', models.CharField(choices=[('APARTMENT', 'Apartment'), ('DETATCHED_HOUSE', 'Detatched House'), ('SHARED_HOUSING', 'Shared Housing')], max_length=50)),
                ('household_size', models.PositiveIntegerField(default=1)),
                ('energy_source', models.CharField(choices=[('GRID', 'Grid'), ('SOLAR', 'Solar'), ('NATURAL_GAS', 'Natural Gas'), ('OTHER', 'Other'), ('HYDROELECTRIC', 'Hydroelectric')], max_length=25)),
                ('monthly_consumption', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_energy_use', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleAndHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_saving', models.CharField(choices=[('ALWAYS', 'Always'), ('OFTEN', 'Often'), ('SOMETIMES', 'Sometimes'), ('RARELY', 'Rarely'), ('NEVER', 'Never')], max_length=25)),
                ('water_usage', models.CharField(choices=[('CONSCIOUS', 'Conscious'), ('SOMETIMES', 'Sometimes'), ('RARELY', 'Rarely'), ('NEVER', 'Never')], max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_and_habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingAndGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_purchase', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=25)),
                ('general_purchases', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=25)),
                ('recycling', models.CharField(choices=[('MOST', 'Most'), ('ABOUT_HALF', 'About Half'), ('SOME', 'Some'), ('NONE', 'None')], max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_and_goods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_commute', models.CharField(choices=[('CAR', 'Car'), ('PUBLIC_TRANSPORT', 'Public Transport'), ('BICYCLE', 'Bicycle'), ('WALKING', 'Walking'), ('CARPOOL', 'Carpool')], max_length=25)),
                ('fuel_type', models.CharField(blank=True, choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric')], max_length=25, null=True)),
                ('commute_distance', models.PositiveIntegerField(default=0)),
                ('air_travel', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_carbon_footprint', models.FloatField(default=0.0)),
                ('yearly_carbon_footprint', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('transportation_emissions', models.FloatField(default=0.0)),
                ('home_energy_emissions', models.FloatField(default=0.0)),
                ('food_emissions', models.FloatField(default=0.0)),
                ('shopping_emissions', models.FloatField(default=0.0)),
                ('waste_emissions', models.FloatField(default=0.0)),
                ('lifestyle_emissions', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_disposal', models.CharField(choices=[('DAILY', 'Daily'), ('EVERY_FEW', 'Every Few Days'), ('WEEKLY', 'Weekly')], max_length=25)),
                ('composting', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('PLANNING_TO', 'Planning To')], max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_management', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
