# Generated by Django 5.1.1 on 2024-11-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_foodanddiet_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodanddiet',
            name='goal',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.FloatField(default=0, help_text="User's daily carbon footprint goal (in kg CO₂)"),
        ),
    ]
