# Generated by Django 5.1.1 on 2024-11-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_foodanddiet_goal_userprofile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.FloatField(blank=True, help_text="User's daily carbon footprint goal (in kg CO₂)", null=True),
        ),
    ]
