# Generated by Django 5.1.1 on 2024-11-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_userprofile_goal_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='user_profile',
            new_name='user',
        ),
    ]
